# frozen_string_literal: true

source "https://rubygems.org"

gem "regular_expression", path: "../"
gem "sinatra"

group :test, :development do
  gem "rack-test"
  gem "rspec-core"
  gem "rspec-expectations"
end
