# frozen_string_literal: true

require "fiddle"
require "fisk"
require "fisk/helpers"
require "set"
require "stringio"
require "strscan"

require_relative "./regular_expression/ast"
require_relative "./regular_expression/bytecode"
require_relative "./regular_expression/cfg"
require_relative "./regular_expression/phases/uncommon"
require_relative "./regular_expression/phases/dead"
require_relative "./regular_expression/character_type"
require_relative "./regular_expression/dfa"
require_relative "./regular_expression/flags"
require_relative "./regular_expression/interpreter"
require_relative "./regular_expression/lexer"
require_relative "./regular_expression/match_data"
require_relative "./regular_expression/nfa"
require_relative "./regular_expression/ignore_case"
require_relative "./regular_expression/parser"
require_relative "./regular_expression/pattern"
require_relative "./regular_expression/scheduler"
require_relative "./regular_expression/version"

require_relative "./regular_expression/compiler/ruby"
require_relative "./regular_expression/compiler/x86"
require_relative "./regular_expression/compiler/cranelift"
