# frozen_string_literal: true

source "https://rubygems.org"

gem "graphviz"
gem "puma"
gem "regular_expression", path: "../"
gem "sinatra"

group :test, :development do
  gem "minitest"
  gem "rack-test"
  gem "rake"
  gem "simplecov"
end
