#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.5.2
# from Racc grammar file "".
#

require 'racc/parser.rb'
module RegularExpression
  class Parser < Racc::Parser

module_eval(<<'...end parser.y/module_eval...', 'parser.y', 103)

  def parse(str)
    @tokens = Lexer.new(str).tokens
    do_parse
  end

  def next_token
    @tokens.shift
  end
...end parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
     3,    47,     9,    10,    20,    12,    48,    13,    14,    15,
    16,    17,    18,    19,    30,    33,    52,    34,    35,    53,
    36,    33,    22,    34,    35,    37,    36,     9,    10,    41,
    12,    40,    13,    14,    15,    16,    17,    18,    19,     9,
    10,    39,    12,    43,    13,    14,    15,    16,    17,    18,
    19,     9,    10,    45,    12,    49,    13,    14,    15,    16,
    17,    18,    19,     9,    10,    50,    12,    51,    13,    14,
    15,    16,    17,    18,    19,    33,    54,    34,    35,    26,
    36,    27,    28,    29,    26,    55,    27,    28,    29 ]

racc_action_check = [
     0,    40,     0,     0,     1,     0,    40,     0,     0,     0,
     0,     0,     0,     0,    12,    30,    47,    30,    30,    47,
    30,    12,     5,    12,    12,    20,    12,     3,     3,    26,
     3,    26,     3,     3,     3,     3,     3,     3,     3,     6,
     6,    24,     6,    31,     6,     6,     6,     6,     6,     6,
     6,    10,    10,    34,    10,    41,    10,    10,    10,    10,
    10,    10,    10,    22,    22,    42,    22,    45,    22,    22,
    22,    22,    22,    22,    22,    32,    49,    32,    32,    11,
    32,    11,    11,    11,    39,    52,    39,    39,    39 ]

racc_action_pointer = [
    -2,     4,   nil,    23,   nil,    19,    35,   nil,   nil,   nil,
    47,    63,    12,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    25,   nil,    59,   nil,    35,   nil,    17,   nil,   nil,   nil,
     6,    35,    66,   nil,    40,   nil,   nil,   nil,   nil,    68,
   -11,    41,    57,   nil,   nil,    56,   nil,     2,   nil,    59,
   nil,   nil,    68,   nil,   nil,   nil ]

racc_action_default = [
    -2,   -39,    -1,   -39,    -4,    -6,    -8,    -9,   -10,   -11,
   -39,   -15,   -39,   -18,   -19,   -20,   -21,   -22,   -23,   -24,
   -39,    -3,   -39,    -7,   -39,   -14,   -39,   -36,   -37,   -38,
   -39,   -39,   -26,   -27,   -29,   -30,   -31,    56,    -5,   -13,
   -39,   -39,   -39,   -17,   -25,   -39,   -12,   -39,   -35,   -39,
   -16,   -28,   -39,   -33,   -34,   -32 ]

racc_goto_table = [
    25,     4,    31,     1,    21,     2,    23,   nil,   nil,   nil,
   nil,    24,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    42,   nil,    44,    38,   nil,   nil,   nil,   nil,    46 ]

racc_goto_check = [
     8,     3,    10,     1,     3,     2,     4,   nil,   nil,   nil,
   nil,     3,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    10,   nil,    10,     3,   nil,   nil,   nil,   nil,     8 ]

racc_goto_pointer = [
   nil,     3,     5,     1,     0,   nil,   nil,   nil,   -11,   nil,
   -10,   nil ]

racc_goto_default = [
   nil,   nil,   nil,   nil,     5,     6,     7,     8,   nil,    11,
   nil,    32 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 22, :_reduce_1,
  0, 22, :_reduce_2,
  2, 23, :_reduce_3,
  1, 23, :_reduce_4,
  3, 24, :_reduce_5,
  1, 24, :_reduce_6,
  2, 25, :_reduce_7,
  1, 25, :_reduce_8,
  1, 26, :_reduce_none,
  1, 26, :_reduce_none,
  1, 26, :_reduce_11,
  4, 27, :_reduce_12,
  3, 27, :_reduce_13,
  2, 28, :_reduce_14,
  1, 28, :_reduce_15,
  4, 30, :_reduce_16,
  3, 30, :_reduce_17,
  1, 30, :_reduce_18,
  1, 30, :_reduce_19,
  1, 30, :_reduce_20,
  1, 30, :_reduce_21,
  1, 30, :_reduce_22,
  1, 30, :_reduce_23,
  1, 30, :_reduce_24,
  2, 31, :_reduce_25,
  1, 31, :_reduce_26,
  1, 32, :_reduce_27,
  3, 32, :_reduce_28,
  1, 32, :_reduce_29,
  1, 32, :_reduce_30,
  1, 32, :_reduce_31,
  5, 29, :_reduce_32,
  4, 29, :_reduce_33,
  4, 29, :_reduce_34,
  3, 29, :_reduce_35,
  1, 29, :_reduce_36,
  1, 29, :_reduce_37,
  1, 29, :_reduce_38 ]

racc_reduce_n = 39

racc_shift_n = 56

racc_token_table = {
  false => 0,
  :error => 1,
  :CARET => 2,
  :PIPE => 3,
  :ANCHOR => 4,
  :LPAREN => 5,
  :RPAREN => 6,
  :LBRACKET => 7,
  :RBRACKET => 8,
  :CHAR_CLASS => 9,
  :CHAR_TYPE => 10,
  :CHAR => 11,
  :COMMA => 12,
  :DASH => 13,
  :INTEGER => 14,
  :PERIOD => 15,
  :LBRACE => 16,
  :RBRACE => 17,
  :STAR => 18,
  :PLUS => 19,
  :QMARK => 20 }

racc_nt_base = 21

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "CARET",
  "PIPE",
  "ANCHOR",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "CHAR_CLASS",
  "CHAR_TYPE",
  "CHAR",
  "COMMA",
  "DASH",
  "INTEGER",
  "PERIOD",
  "LBRACE",
  "RBRACE",
  "STAR",
  "PLUS",
  "QMARK",
  "$start",
  "target",
  "root",
  "expression",
  "subexpression",
  "item",
  "group",
  "match",
  "quantifier",
  "match_item",
  "character_group_items",
  "character_group_item" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'parser.y', 6)
  def _reduce_1(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 8)
  def _reduce_2(val, _values, result)
     result = nil
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 12)
  def _reduce_3(val, _values, result)
     result = AST::Root.new(val[1], at_start: true)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 14)
  def _reduce_4(val, _values, result)
     result = AST::Root.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 18)
  def _reduce_5(val, _values, result)
     result = [AST::Expression.new(val[0])] + val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 20)
  def _reduce_6(val, _values, result)
     result = [AST::Expression.new(val[0])]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 24)
  def _reduce_7(val, _values, result)
     result = [val[0]] + val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 26)
  def _reduce_8(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

# reduce 9 omitted

# reduce 10 omitted

module_eval(<<'.,.,', 'parser.y', 32)
  def _reduce_11(val, _values, result)
     result = AST::Anchor.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 36)
  def _reduce_12(val, _values, result)
     result = AST::Group.new(val[1], quantifier: val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 38)
  def _reduce_13(val, _values, result)
     result = AST::Group.new(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 42)
  def _reduce_14(val, _values, result)
     result = AST::Match.new(val[0], quantifier: val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 44)
  def _reduce_15(val, _values, result)
     result = AST::Match.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 48)
  def _reduce_16(val, _values, result)
     result = AST::CharacterGroup.new(val[2], invert: true)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 50)
  def _reduce_17(val, _values, result)
     result = AST::CharacterGroup.new(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 52)
  def _reduce_18(val, _values, result)
     result = AST::CharacterClass.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 54)
  def _reduce_19(val, _values, result)
     result = AST::CharacterType.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 56)
  def _reduce_20(val, _values, result)
     result = AST::Character.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 58)
  def _reduce_21(val, _values, result)
     result = AST::Character.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 60)
  def _reduce_22(val, _values, result)
     result = AST::Character.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 62)
  def _reduce_23(val, _values, result)
     result = AST::Character.new(val[0].to_s)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 64)
  def _reduce_24(val, _values, result)
     result = AST::Period.new
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 68)
  def _reduce_25(val, _values, result)
     result = [val[0]] + val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 70)
  def _reduce_26(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 74)
  def _reduce_27(val, _values, result)
     result = AST::CharacterClass.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 76)
  def _reduce_28(val, _values, result)
     result = AST::CharacterRange.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 78)
  def _reduce_29(val, _values, result)
     result = AST::Character.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 80)
  def _reduce_30(val, _values, result)
     result = AST::Character.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 82)
  def _reduce_31(val, _values, result)
     result = AST::Character.new(val[0].to_s)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 86)
  def _reduce_32(val, _values, result)
     result = AST::Quantifier::Range.new(val[1], val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 88)
  def _reduce_33(val, _values, result)
     result = AST::Quantifier::AtLeast.new(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 90)
  def _reduce_34(val, _values, result)
     result = AST::Quantifier::Range.new(0, val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 92)
  def _reduce_35(val, _values, result)
     result = AST::Quantifier::Exact.new(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 94)
  def _reduce_36(val, _values, result)
     result = AST::Quantifier::ZeroOrMore.new
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 96)
  def _reduce_37(val, _values, result)
     result = AST::Quantifier::OneOrMore.new
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 98)
  def _reduce_38(val, _values, result)
     result = AST::Quantifier::Optional.new
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
end   # module RegularExpression
